### ISSUE TITLE
Jenkins jobs on GitHub are marked failed when at least one really fails and others succeed - this dismays

### ISSUE THREAD

**Issue by kuvaldini** [hyperledger/iroha#1082]
## What we see

<img width="945" alt="изображение" src="https://user-images.githubusercontent.com/47349143/121958298-338d6a80-cd6c-11eb-87f1-4dd066ac0300.png">

<img width="1421" alt="изображение" src="https://user-images.githubusercontent.com/47349143/121960659-0ee6c200-cd6f-11eb-9563-c56bb4a58877.png">

## What should be
GitHub **must** show succeeded jobs as succeeded, failed as failed. Jobs statuses must correspond.

----
polite ping to @kamilsa @BulatSaif @lebdron

**Comment by BulatSaif** [comment]
The problem is in this line (https://github.com/hyperledger/iroha/blob/main/Jenkinsfile#L70), it is using the global variable `currentBuild.currentResult`, any build which runs in parallel(https://github.com/hyperledger/iroha/blob/main/Jenkinsfile#L488) can edit it.
possible fix: 
1. create a global map `customBuildStatus` and store the build results there, and use it to notify git:
`gitNotify ("Jenkins: " + build.name, customBuildStatus[build.name]:?currentBuild.currentResult, 'FAILURE')`

or

2. Remove all git Notify and left only one, since the results are the same

**Comment by kuvaldini** [comment]
And the other similar problem 
there are only 2 tests failed but github reports 7 failed 2 succeeded and 3 started but never finished.

screenshots from https://github.com/hyperledger/iroha/pull/943 and https://jenkins.soramitsu.co.jp/blue/organizations/jenkins/iroha%2Firoha-hyperledger/detail/PR-943/78/pipeline

<img width="1459" alt="изображение" src="https://user-images.githubusercontent.com/47349143/122232724-208dae00-cec4-11eb-85cd-fe84ce1a193f.png">

<img width="882" alt="изображение" src="https://user-images.githubusercontent.com/47349143/122233032-6480b300-cec4-11eb-949b-17f5bc727f3b.png">

**Comment by BulatSaif** [comment]
>  3 started but never finished.

This happens then GitHub is down or not available and it didn't receive notification about the finish
