### ISSUE TITLE
Iroha Event Triggers - MVP

### ISSUE THREAD

**Issue by eadventurous** [hyperledger/iroha#1124]
Create a new feature - users should be able to set up event triggers and listeners for time, block or world state view changes.

RFC: https://wiki.hyperledger.org/display/iroha/Permissions+and+Event+Listeners

**Comment by s8sato** [comment]
#### The followings is about `User` Level Triggers.

* My current understanding is as follows.
I'd like to fill `?` in the following table

  |  | when registration | when execution |
  | -- | -- | -- |
  | validate condition? | ? | Never |
  | validate instruction? | ? | Never |
  | take fee? | Surely | Maybe |


* If instruction is wasm blob, validator should have complexity equal to or greater than current one, right?

* What will be the representation of condition?
I guess it is almost `Expression`

* Some crazy conditions like "every 1 millisecond" may prevented by fee.
And what if a person go insane and don't care about economy?
Maybe can handle by charging non-linearly rising fee against frequency?

* Registration fee can depend on blob size,
not on computation cost (how to estimate?),
because only the user pays the computation cost, right?

* About implementation.
Will triggers hold specific field in world, domain and else?
Or what if we introduced trigger as an executable asset?
Of course it would require representative account(resp.domain) for domain(resp.world)

**Comment by eadventurous** [comment]
Closing the epic as Triggers were decomposed into issues and the RFC is accepted https://wiki.hyperledger.org/display/iroha/Triggers
