### ISSUE TITLE
Remove structopt from core Iroha

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#1249]
We need to replace it with custom `iroha_cli_args` crate or module. As we strive to have bare minimum of libraries in core.

**Comment by appetrosyan** [comment]
This is problematic at present due to the structure of the `p2p` crate. It may become feasible after a re-factor.

**Comment by eadventurous** [comment]
The issue is a bit outdated. Currently we use struct opt in core for the argument parsing. And it might take some time to reimplement it. Previously with clap it was easier as there were only a couple of arguments. Generally I think we should discuss on the planning meeting if this issue still makes sense.

**Comment by eadventurous** [comment]
Also @appetrosyan I am not sure how is it connected to the p2p crate?

**Comment by appetrosyan** [comment]
argh might be a good starting point. It is optimised for code size, so I doubt that any feature parity can be achieved by hand-rolling an implementation. 

https://crates.io/crates/argh

**Comment by appetrosyan** [comment]
Another potential option is to remove argument parsing altogether, and instead use `iroha_cli` as a program that accepts the config file from `STDIN`, or via the `configuration` endpoint. We can avoid `STIDN` too if we instead write a shell script that converts a `config.json` into the proper environment variables.
