### ISSUE TITLE
Failed to parse genesis.block

### ISSUE THREAD

**Issue by MikhailMe** [hyperledger/iroha#1431]
I try launch iroha daemon and got this error.
Before run command I changed genesis.block
New genesis.block is valid Json file, but it doesn't work.

Here is link to my genesis.block: https://gist.github.com/MikhailMe/3da894d91df7d7ba559ae6b26440fb5b

![image](https://user-images.githubusercontent.com/10109191/41101013-9429b112-6a6b-11e8-866b-771a87d6c958.png)

**Comment by l4l** [comment]
Amount value is represented as uint256:
https://github.com/hyperledger/iroha/blob/86a8c01bc2784371f8425770eed42e8916acd46d/schema/primitive.proto#L97

and uint256 itself is not built-in type, so you need to set it up as well:
https://github.com/hyperledger/iroha/blob/86a8c01bc2784371f8425770eed42e8916acd46d/schema/primitive.proto#L89-L94

[Here's](https://gist.github.com/l4l/f3502261c759625d1486f312503b58dd/revisions#diff-3121b4980b0420247f995734e05e1fb9L117) the fix for your genesis

Though, I think we should print more detailed error here

**Comment by MikhailMe** [comment]
Thanks a lot, this is works
I am closing issue
