### ISSUE TITLE
`Expression` strong typing

### ISSUE THREAD

**Issue by rkharisov** [hyperledger/iroha#1568]
In Iroha2 we have `Expressions`, which variants have members eventually evaluated to some `Value`. For example `Expression::Add(Add)` will evaluate to `Value::U32(u32)`. But in schema currently no way to figure out in what type some expression will be evaluated. Because of it clients do not have compile time (or at least runtime) checks if some expression will be evaluated to required type.

I propose to represent in schema in which type `Expression` can be evaluated. 
Currently `Expression` represented like
```json
"iroha_data_model::expression::Expression": {
  "Enum": {
    "variants": [
      {
        "name": "Add",
        "discriminant": 0,
        "ty": "iroha_data_model::expression::Add"
      },
```
Suggested variant
```json
"iroha_data_model::expression::Expression": {
  "Enum": {
    "variants": [
      {
        "name": "Add",
        "discriminant": 0,
        "ty": "iroha_data_model::expression::Add<u32>"
      },
...
  "iroha_data_model::expression::Add<u32>": {
    "Struct": {
      "declarations": [
```

**Comment by 0x009922** [comment]
I've made some research, and it turned out that even from Rust's side there neither runtime nor compile errors with this code:

```rust
use iroha_data_model::{expression, Value};

fn main() {
    let exp = expression::Expression::Add(expression::Add {
        left: Value::Bool(false).into(),
        right: Value::U32(4123).into(),
    });

    println!("{:?}", exp);
}
```
Print:
```
Add(Add { left: EvaluatesTo { expression: Raw(Bool(false)), _value_type: PhantomData }, right: EvaluatesTo { expression: Raw(U32(4123)), _value_type: PhantomData } })
```

While implementing SCALE-codec and Iroha data-model libraries I focus on adopting Rust's type system itself, and here I see that this type system doesn't give a guarantee that constructed expression will not fail at runtime. I guess in Rust's implementation there are some more type-safe ways to construct expressions, but... I used the most clearest way (afaik) to do it and idk where is this type-safe way.

@rkharisov, could you explain how `Expression` typing works in your Kotlin implementation?

**Comment by rkharisov** [comment]
Currently in Kotlin SDK all `Expression` are not type safe and it is up to developer create `Expression` with proper evaluated type. If there will be some mistake, it can be only checked in runtime on peer. So the purpose of this  issue to expose the actual evaluated type in schema. 

You are right - peer itself have only runtime checks if evaluated type is the same as expected. But still I believe it can prevent of making a lot of mistakes if it will be possible to check correctness of evaluated type on client side. So I think this issue is still actual and need to be implemented
