### ISSUE TITLE
Review documentation for terms consistency and grammar issues

### ISSUE THREAD

**Issue by thaddeus-cambron** [hyperledger/iroha#1580]
http://iroha.readthedocs.io/en/latest/ requires grammar and term consistency review and grammar changes. Feel free to assign this issue to me.

**Comment by l4l** [comment]
Indeed, the documentation is not perfect and you are very welcome to contribute. If you'd like discuss/clarify any terms you may ask for them either here, or at any of our chat ([gitter](https://gitter.im/hyperledger-iroha/Lobby), [rocket](https://chat.hyperledger.org/channel/iroha), or [telegram](https://t.me/hyperledgeriroha)).

If you are really interested in contribution, please perform correction by some "reviewable pieces" (e.g up to 100 loc in diff). Otherwise it might be hard to check for maintainers, thus merging of the PR may go to nowhere.
Setup for building docs described at [related readme](https://github.com/hyperledger/iroha/tree/develop/docs), and the PRs must based on the `develop` branch. Feel free to ask any additional questions.

And thank you for your initiative!

**Comment by thaddeus-cambron** [comment]
This makes sense. Thank you for the direction.

**Comment by neewy** [comment]
@thaddeus-cambron hi! Happy to hear that you can help with grammar issues and consistency. Are there any updates?

**Comment by thaddeus-cambron** [comment]
The following is a gist I created for review,  prior to initiating a PR:
https://gist.github.com/thaddeus-cambron/4f337191e89cdfe4cdf698372631d9f7

**Comment by l4l** [comment]
@thaddeus-cambron it's pretty hard to review such fixes without pr, moreover such comments might be missing (as you see there was no response for a 3 weeks)

**Comment by thaddeus-cambron** [comment]
I am working directly with @igor-egorov. This work was set up through the Hyperledger Training & Education Working Group. and @igor-egorov through a Google Doc.

**Comment by LiraLemur** [comment]
Igor told me we could close this issue. Thank you!
