### ISSUE TITLE
Reconsider broker model RFC

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#1769]
> S Sato, [2021/12/28 23:58]
> The current broker model has a couple of channels:
> producer-broker and broker-consumer.
> I think the equivalent is achieved with single watch::channel.
> 
> Also planning to:
> - Introduce Producer and Consumer traits
> - Introduce an optional backtrace to an event to expect the result

EDIT:
"a couple of channels" was my misunderstanding -- there was only broker-subscriber channels from the beginning.
Still, another optimization could be to reduce access to the broker

**Comment by s8sato** [comment]
Related to:
- #2012
- #2060
- #2043
- #1218

**Comment by SamHSmith** [comment]
Do you know how much use we get out of having a broker? To my knowledge we actually never subscribe to the same type of message twice. Since the only `Broker::` functions we use `subscribe` and `issue_send` combined with the fact that there are never 2 subscribers to the same event, maybe we could replace all uses of `Broker` with a simple `mpsc` channel?

**Comment by s8sato** [comment]
> never subscribe to the same type of message twice

It cannot be said that a `BrokerMessage` will never have 2 subscribers in the future.
We don't even have all of the major components (e.g. Hijiri) yet.
I'd add here that `BrokerMessage` could be consolidated with `Event`

> replace all uses of Broker with a simple mpsc channel?

Yeah, speaking of a single channel, my idea is:
- Broker does not have any `Sender`
- Broker only has `Receiver`s
  - `Receiver<Msg>` is passed by a publisher at the declaration to publish `Msg`s
  - Broker clones and passes `Receiver<Msg>` to subscribers at the subscription request for `Msg`s
