### ISSUE TITLE
Peer suspicion is needed

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#185]
Given 4 servers in the following validation chain:

**A** --- **B** --- **C** --- **D**

{**A**,**B**,**C**} will be the validators (with **C** as the *proxy tail*).

If an error occurs in validation it is important to be able to assert blame, for example, if **B** receives a transaction and then doesn't validate it, then **B** has a fault and should be moved to the end of the validation chain.

This can be accomplished by signing transactions when they are received, sending cryptographic proof of receipt back to the sender. 

For example, if **A** sends a transaction to **B**, then **B** signs the hash of the transaction with its private key, sending just the signature back to **A**. If **B** never sends the transaction to **C** or lies and says that **A** never sent it, **A** can use the signed receipt from **B** to prove to the other peers that **B** is the faulty server and then they can execute a view change that reorders the peers.

**Comment by Warchant** [comment]
Is this closed by #192 ?

**Comment by Warchant** [comment]
Do not close this until we have tests for this.

**Comment by satellitex** [comment]
Test to connect 1 or N nodes to existing network.

1. Setup`iroha-main` in iroha-docker.
2. Any node setup iroha-1, iroha-2, ...iroha-N
3. Execute `./bin/issue_transaction add peer iroha2-key iroha2-pubkey 0.0 false` in iroha-1.
4. Similarly `3` add peer up to iroha-N.

**Comment by takemiyamakoto** [comment]
Can you add this to circle-ci?

**Comment by satellitex** [comment]
I try it.
But I can be going to do after merge execute.

**Comment by takemiyamakoto** [comment]
Is this done?

**Comment by l4l** [comment]
doesn't seem to be
at least blocked by #209

**Comment by takemiyamakoto** [comment]
Is this done now?

**Comment by l4l** [comment]
Well it can be considered as completed **but** it still lack of tests and that is very bad. And it's an issue why it easily cannot be done.

Current structure of `connection_with_grpc` is enormous and doesn't allow to write proper tests.
steps so far to complete are:
- [ ] Remove any logic (also good to refactor as well) of signing/validating from `connection_with_grpc` and dedicate this task to its users
- [ ] Write & check tests

Actually this can be separated to the other issue because this one should work now

**Comment by l4l** [comment]
ah, yeah
As we are planning to migrate to fbs in few days this will be fixed anyway, so i'm closing this one
