### ISSUE TITLE
Implement missing `kura` init modes. 

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1915]
Kura currently has a `fast` and `strict` init mode, but both do the exact same thing. Given that the block storage had been optimised by @SamHSmith we should consider further improving the boot-up times and add a quick mode that skips some checks.

**Comment by SamHSmith** [comment]
While simplifying kura in issue #2376, it dawned on me that the best way to store the blockchain is a two file system. A data file stores the blocks one after the other. A seperate index file contains an array of "BlockInfo" structs that specify where in the data file each block is stored.

This new method of storage is simpler and easier to implement. It also enable easy addition of multiple init modes. A strict initialization is always serially dependent because each block must be verified one after the other as they affect the world state view. A loose init involves loading the index into memory then verify the hashes of every block in the chain in a parallel fashion.

**Comment by SamHSmith** [comment]
The information I have written above is not correct. Fast init should be implemented as the loading of a cached WorldState from disk. It should also start an "audit" inside kura that runs in the background and verifies that the disk loaded WorldState is valid.

**Comment by appetrosyan** [comment]
> Fast init should be implemented as the loading of a cached WorldState from disk. It should also start an "audit" inside kura that runs in the background and verifies that the disk loaded WorldState is valid. 

That would make it a `deferred` rather than `fast` init mode.
