### ISSUE TITLE
Debug potentially incorrect return Value in Kotlin SDK for `FindAccountsByDomainId`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#1969]
The result of executing `FindAccountsByDomainId` may sometimes return objects other than `DomainId`. `U32` is returned as a `Value`, meaning that either the Kotlin SDK mishandles the datatype and converts it into a Value, or Iroha itself produces an incorrect data structure. 

![image.png](https://images.zenhubusercontent.com/615ecfcf34e89aca674dc2ac/fd073d26-f713-4ba9-84ae-af6b1fe59b18)

**Comment by mversic** [comment]
@arndey would it be possible to get unparsed query output? Just raw bytes so that I can confirm it was deserialized properly

**Comment by appetrosyan** [comment]
Rebasing onto the release `f58992e` resolved the issue.

**Comment by mversic** [comment]
I'm still experiencing the exact same issue

**Comment by mversic** [comment]
the issue arises due to mismatch of compilation flags (namely `roles` flag) between server and client when compilation flags affect inclusion/exclusion of the fields/variants of data model structures.

Best course of action is to remove conditional layout of data model structures altogether and have clients support all features while server should reject request it cannot fulfill

**Comment by mversic** [comment]
server should be able to generate a valid response to any request regardless of which feature flag it was compiled with, though it may not be able to fulfill the incoming request
