### ISSUE TITLE
Disallow empty `Identifiers`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#2000]
At the moment it is allowed to create empty `Name`, `DomainId`, `AccountId`, etc. Should we continue to allow empty string identifiers or should we forbid them. What about using `Option`? 

It should be noted that empty string is a well defined identifier

**Comment by ales-tsurko** [comment]
@mversic @appetrosyan could you clarify this issue?

> It should be noted that empty string is a well defined identifier

So `Name` type is allowed to have empty string? But in which case `AccountId` can be empty? And is it possible, for example, to have `AccountId` like `""@""`? So we should require non-empty strings for **some** types? I mean, should we forbid, for example, using empty name and domainID for `AccountId`, or forbid name to be empty for `DomainId` (because it's the only field), but still allow `Name` to be empty?

**Comment by appetrosyan** [comment]
To me it seems that the sole purpose of the `Name` struct is to encapsulate that some valid strings are invalid identifiers. As such an empty identifier is not a valid Name. Thus, we should allow an empty constString, but not an empty Name.
