### ISSUE TITLE
Support querying for blocks and transactions

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2103]
In Iroha Block Explorer, we need to show up to a user the list of latest blocks and transactions. Also it would be useful to query for some specific block/transaction by its id, height and hash relatively.

Thus, it would be nice to extend Query API with the following:

- `FindAllBlocks`, that returns a list of blocks. With pagination, of course. Ordered by height desc.

  There are several life stages of a block:

  1. pending
  2. chained
  3. valid
  4. committed

  AFAIK in explorer we only need pending and committed blocks, and we need to distinguish them from each other.

- `FindBlockByHeight`, that returns a single block if it has been found. I think we need to know the block status here as well. 
- `FindAllTransactions`, that returns a list of latest transactions, ordered by timestamp desc. **The most debatable query**. 

  I am not sure that this query is a good idea, because actually transactions are always contained within blocks, and its enough to query for blocks only to get transactions as well. But if we want to show the list of transactions decoupled from their blocks, how to paginate this data independently from blocks? Maybe we should drop the idea of "transactions list" decoupled from blocks.

- `FindTransactionByHash`, that returns a single transaction if it has been found. This is not as debatable as `FindAllTransactions` is, but I think it might be really hard to query for it in an efficient way. Am I right?

**Comment by appetrosyan** [comment]
- `FindTransactionByHash` is there since #1517. 
- `FindAllTransactions` has some overlap with `FindAllBlocks`. Still, because of the difference in pagination and how it would be a nightmare to implement `FindAllTransactions` given only a paginated `FindAllBlocks` I think we should implement both. 
- `FindBlockByHeight` is redundant. Pagination has a lower and upper bound. `FindAllBlocks` can be used to get blocks of height _n_ to _n+1_ and it would have the same effect.

**Comment by appetrosyan** [comment]
- `FindTransactionByHash` is there since #1517. 
- `FindAllTransactions` has some overlap with `FindAllBlocks`. Still, because of the difference in pagination and how it would be a nightmare to implement `FindAllTransactions` given only a paginated `FindAllBlocks` I think we should implement both. 
- `FindBlockByHeight` is redundant. Pagination has a lower and upper bound. `FindAllBlocks` can be used to get blocks of height _n_ to _n+1_ and it would have the same effect.

**Comment by appetrosyan** [comment]
@QuentinI If you're looking for something new to implement, seems like a good place to start

**Comment by s8sato** [comment]
Does [block stream](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md#blocks-stream) not work for it?

**Comment by QuentinI** [comment]
Regarding `FindAllBlocks`: structures describing blocks are in defined in `iroha_core`, which depends on `iroha_data_model` where the queries need to be defined.
As far as I understand, `iroha_data_model` doesn't concern itself with blocks at all at the moment. Do we actually want to change that, or is [`/block/stream`](https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/references/api_spec.md#blocks-stream) API endpoint @s8sato mentioned sufficient here? My take would be that `/block/stream` should suffice if we need this information only for Block Explorer.

**Comment by appetrosyan** [comment]
@0x009922 You're probably the best person to explain what's missing in the block streaming API.
