### ISSUE TITLE
Add dedicated build machine

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2175]
@mversic

**Comment by mversic** [comment]
The suggestion here is to have a machine (e.g. ec2 instance) where our team member would be able to SSH into and build the code remotely, or run tests. The reason is that build (especially with `release` profile) takes a long time, and consumes a lot of disk space, on a local machine. This is especially true when building whole of Iroha with `cargo test`. Main premise here is that the build on a dedicated machine would perform significantly faster compared to it being done locally. I also think that user separation (in linux space) on the machine would be preferable, but we can make a quasi separation with one folder assigned to each team member

**Comment by appetrosyan** [comment]
@Cre-eD

**Comment by Cre-eD** [comment]
> @Cre-eD Should we use the kubernetes cluster for this?

What's the resource requirement?
