### ISSUE TITLE
Rewrite world mocking

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#2292]
World mocking using `WorldTrait` is quite painful and causes some problems and inconsistency especially after merge of https://github.com/hyperledger/iroha/pull/2284

We need to find another way to mock `World` for tests. 
Some solutions I can see right now:

1. Use [mockall crate](https://crates.io/crates/mockall)
2. Remove mocking at all and do some test runtime preparation using genesis, instructions and other supported things
3. Like 2 but use procedural macro for that

**Comment by appetrosyan** [comment]
The option 1. should be the first thing that we try. We don't want to maintain a separate non-compliant mocking library inside of Iroha. To me this is a relatively large change, so we should put this off until after the LTS is released. 

The option 2 is something that we will need to do eventually, since `test_network` only crudely approximates the behaviour of a real system. I think that we need to have a lot more **real** integration tests, and improve the coverage with unit tests.
