### ISSUE TITLE
Add possibility to get transaction's block hash when querying it

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#2301]
## Motivation

In the Iroha Explorer, we fetch transactions with `FindAllTransactions` query, and we want to know to what block each of them belongs to.

## Possible solutions

- **(the most preferable)** In `FindAllTransactions` query return not `Vec<TransactionValue>` but some other struct like:

  ```rust
  struct TransactionExt {
    tx: TransactionValue,
    block_hash: Hash
  }
  ```

- Extend `Transaction` or `RejectedTransaction`  structures with `block_hash` field
- Extend general `TransactionValue` with `block_hash` field (i.e. make it struct instead of enum)

**Comment by appetrosyan** [comment]
https://github.com/omkar-mohanty showed interest

**Comment by omkar-mohanty** [comment]
Hi I want to work on this!

**Comment by appetrosyan** [comment]
The two latter approaches to me seem untenable. 

> Extend Transaction or RejectedTransaction structures with a `block_hash` field

Would open Iroha to an OOM attack. 

> Extend general TransactionValue with block_hash field (i.e. make it struct instead of enum

Which is slightly better, but to me still problematic in terms of memory. 

Since the block hash is implicit, we don't need to store it, so my suggestion would be to compose the block hash into the TX value only in the query.
