### ISSUE TITLE
docker compose with 4-peers doesn't get gracefully shut down

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2303]
The most likely culprit is that the `SIGINT` signal (from Control + C) doesn't get forwarded beyond the first process, leading to non-graceful shutdown on all but the first process. 

![image](https://user-images.githubusercontent.com/15856657/171379549-a452a635-a35a-4287-80c3-9c404e239d9d.png)

**Comment by mversic** [comment]
is this related to #1926 ?

**Comment by appetrosyan** [comment]
Seems like it is.

**Comment by pesterev** [comment]
If you build images with `docker-compose-local.yml`, then the problem is not reproduced. But it is reproduced with the `docker-compose.yml` where isn't `init: true` property.

I've tested `docker-compose.yml` with `init: true` and yeah the problem is no longer reproduced.
[The doc](https://docs.docker.com/compose/compose-file/#init) explains why.

**Comment by pesterev** [comment]
Might be reopened
