### ISSUE TITLE
Coherence in Asset registration

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2339]
That was deliberate, actually, because I wanted to propose restricting registering an asset to a default value (either per value type or per asset definition). So I tried to leave Mints as pairs of Register+Mint here rather than replacing the Mint.

_Originally posted by @QuentinI in https://github.com/hyperledger/iroha/pull/2333#discussion_r892076104_

**Comment by appetrosyan** [comment]
This seems to be the right approach. Registering an asset is not the same as minting an asset to a specific wallet. 

It should also be noted that we no longer require for something to be registered in order for it to be Minted, which IMO is a bit of a security risk. This increases the surface area for mint instructions in the permission validators, it makes the process unnecessarily more complex.

**Comment by QuentinI** [comment]
> It should also be noted that we no longer require for something to be registered in order for it to be Minted
 
After #2333 we _will_ have to register assets before minting.
 
 I'm still not sure registering assets to specific accounts makes sense, but assuming we want it, I do think it should be semantically different from minting and create asset with default value. Depending on how flexible we want it to be, it can either be a predefined value for each `AssetValue` variant or defined per-asset in `AssetDefinition`.
 
Relatedly, I only now noticed #2333 as is makes it possible to mint non-mintable assets twice, because you can first set arbitrary value for it when registering, and then mint it. If we decide to stick to register having arbitrary value, we could just prohibit minting non-mintable assets althogether, which will result in desired behaviour; but I'm not sure what we could do otherwise.

**Comment by appetrosyan** [comment]
For the record I have not yet made a decision. I think we need to brainstorm a few ideas and maybe poll a few times.

**Comment by QuentinI** [comment]
Considering registration I would say you need to register asset definition, then you can mint without registering asset to account. That actually is how it is now.
#2333 adds support for registering assets to accounts and requires to register it before minting. I was under impression that's what you would like based on [this](https://github.com/hyperledger/iroha/issues/2227#issuecomment-1143275338) comment.

From my perspective the whole idea of registering asset to account is redundant and I don't see why we would want it.

**Comment by mversic** [comment]
If you take NFTs in the picture it would make sense to allow for the initial value to be set when registering an asset to an account. We also wouldn't require that `Mintable::Once` which I assume would be a bit confusing to the user. It seems to be that the only reason we've introduced `Mintable::Once` is because we didn't have a way to register an asset with an initial value

**Comment by SamHSmith** [comment]
Maybe an asset registration always includes an implicit minting? So that you can register an asset with initial value and nonmintable, or zero initial value and it is mintable, or a combination. This is what you guys have already said so I guess I'm just joining in.

What is the difference between registering an asset and registering an asset definition? Is it like registering fiat currency vs registering the US dollar? I think we should probably avoid too many layers of indirection. Register asset definition -> register asset -> mint/send asset to people, feels slightly too abstract. And I'm not sure what is gained by having asset definitions, other than "These two assets behave the same". And isn't there a problem of duplicate asset definitions? People registering the same thing many times. Then don't we have to compare asset definitions for equivilance anyway?

**Comment by mversic** [comment]
> Maybe an asset registration always includes an implicit minting? So that you can register an asset with initial value and nonmintable, or zero initial value and it is mintable, or a combination. This is what you guys have already said so I guess I'm just joining in.

We haven't had the suggestion to do both

**Comment by mversic** [comment]
> What is the difference between registering an asset and registering an asset definition? Is it like registering fiat currency vs registering the US dollar?

Registering an asset definition is more like introducing a support for a US dollar savings accounts and registering an asset is opening a savings account for a particular person

**Comment by mversic** [comment]
>And isn't there a problem of duplicate asset definitions? People registering the same thing many times. Then don't we have to compare asset definitions for equivilance anyway?

The equivalence relation is nominal, not structural. So yes, users can define structurally equal asset definitions, but under different names. I find this a desired behavior

**Comment by s8sato** [comment]
> 3. Do we want to register and mint the initial quantity in one instruction or one transaction

Since both are already feasible, I think the requirement is to combine existing instructions to provide encapsulation of commonly used patterns.

5. If I register an asset to an account without registering the definition of the asset to a domain, what does `asset.id.definition_id.domain_id` represent?

**Comment by mversic** [comment]
> 5. If I register an asset to an account without registering the definition of the asset to a domain, what does `asset.id.definition_id.domain_id` represent?

That's not allowed and would produce `FindError`. Asset definition must first be registered and only then can a user assign asset to an account
