### ISSUE TITLE
Design for smart contracts

### ISSUE THREAD

**Issue by takemiyamakoto** [hyperledger/iroha#249]

**Comment by Warchant** [comment]
I propose the following solution:
1. we create unprivileged lxc container with preinstalled *any language* interpretator/compiler and restrictions on disk/networking/memory/syscalls. Underlying FS should be BTRFS (B-Tree FS)
2. when new job arrives (new code execution), we clone original container and start it.
3. we execute smart contract inside lxc-container as unprivileged user.
4. after execution we delete the lxc-container. 

the reason why I selected btrfs is that copying of the container becomes almost free, due to copy-on-write feature of that FS.

in comparison to XFS or EXT4, BTRFS is 2x faster for random writes and 2x slower for random reads.
But I don't think it is a problem, because users will not have (many) disk IO operations in smart contracts.

Thus starting new job becomes free, new containers will not take the disk space and sandboxing level can be manipulated easily.

**Comment by takemiyamakoto** [comment]
If we made our own language, I am thinking something like this:

```
var a = 2 + 3;

var transactionsForAcct = ametsuchi.getTx("38a.....");

var totalSent = sum([tx.value for tx in transactionsForAcct]);
```

**Comment by Warchant** [comment]
It looks like Scala :full_moon_with_face:

**Comment by MizukiSonoko** [comment]
transactionsForAcct.fold(0)((_, _) => _.value + _.value)

**Comment by tkyonezu** [comment]
IMO in the smart contracts which environment should be strictly limited. So, It should not handle any disk storage and network. It should only can handle data in ledger.

**Comment by l4l** [comment]
In slow development, eventually there will be some update, probably not that soon
