### ISSUE TITLE
[FEATURE] Pagination in the order of insertion

### ISSUE THREAD

**Issue by arndey** [hyperledger/iroha#2501]
### GIT commit hash

LTS

### Minimum working example

```rust
fn main() {
     // Steps to reproduce …
     // Steps to reproduce …
}
```

### Expected behaviour

For example: if we have 10 assets and want to paginate it by 5 assets per page -> I'll get `01234 56789`. Then if we add 1 asset I expect to get (where x is a new asset) `x0123 45678 9`

### Actual behaviour

I got `x0123 56478 9` and next time I was running this test I got `01234 x5678 9`

This behavior makes pagination unusable as far as I can see

### Operating system

macos

### Current environment

Docker Hub

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

**Comment by mversic** [comment]
I'm turning this into a feature request. Currently, Iroha returns assets sorted lexicographically present at the time of evaluating the query.

**Comment by pesterev** [comment]
So the ledger always returns a sorted list of assets whenever you make a request (w or w/o pagination). The sorting always is lexicographical (alphabetical). That's why the pages have strange values. To clarify, let me show an example:

1. Alice has a list of assets: ["1", "2", "3", "4", "5", "6", "7", "8", "9"].
2. The client makes a request with pagination (start-index is 5 and limit aka count-of-items is 5) and receives ["1", "2", "3", "4", "5"].
3. Alice creates a new asset with id "10" and submits it to the ledger. Now Alice has the following list of assets: ["1", "10", "2", "3", "4", "5", "6", "7", "8", "9"] because "10" < "2" by the lexicographical sorting.
4. After that, the client wants to receive the next page and makes a new request with the start-index is 5 and the limit is 5 and gets ["5", "6", "7", "8", "9"] so he got "5" again what isn't OK.

I suppose the client wants to receive ["6", "7", "8", "9", "10"] so isn't possible in the current implementation.

**Comment by mversic** [comment]
@arndey you're forcing us to sort assets in insertion order when responding to the paginated `FindAllAssets` query

**Comment by mversic** [comment]
@arndey does [this](https://github.com/hyperledger/iroha/pull/2515/files#diff-07570e07fd265a00103f75fb732226d94128a1f185b34e33908ddf1263f53861R234-R303) test case correctly describe the jist of this issue?

**Comment by Mingela** [comment]
Alternatively we should have a way to specify/customize the logic of sorting since most people interested in pagination generally expect timestamp based sorting so that newest entries (or the ones updated recently) will appear either in the first of the last page

**Comment by arndey** [comment]
> @arndey does [this](https://github.com/hyperledger/iroha/pull/2515/files#diff-07570e07fd265a00103f75fb732226d94128a1f185b34e33908ddf1263f53861R234-R303) test case correctly describe the jist of this issue?

I don't know rust.

**Comment by mversic** [comment]
> I got x0123 56478 9 and next time I was running this test I got 01234 x5678 9

it should be noted that `x` is different in these two runs
