### ISSUE TITLE
[PERFORMANCE BUG] When sending ~ 5000 assets in a row then Iroha 2 down without information in logs.

### ISSUE THREAD

**Issue by arndey** [hyperledger/iroha#2506]
### GIT commit hash

e3cd89bd

### Minimum working example

```rust
fn main() {
     // Steps to reproduce …
     // Steps to reproduce …
}
```

### Expected behaviour

I have a script which creates ~650 assets and then query findAllAssets to print total size. After like ~30k assets script starts to print same size after every new iteration (because findAllAssets returns old data). Btw all requests are sync. But after some  iterations data will be updated and Iroha returns all new assets. But after ~30k assets it doesn't update after every new bunch of assets.

### Actual behaviour

👆👆👆

### Operating system

macos

### Current environment

Docker Hub

### Logs in JSON format

<details>
  <summary>Log contents</summary>
  
  ```json
  Replace this text with a JSON log,
  so it doesn't grow too large and has highlighting.
  ```
</details>

**Comment by pesterev** [comment]
@arndey, could you please share your script (link or copypaste, whatever)? It would be great.

**Comment by pesterev** [comment]
> > @arndey, could you please share your script (link or copypaste, whatever)? It would be great.
> 
> It's written in Kotlin, do you need it?

Yes.

**Comment by pesterev** [comment]
It seems to happen due to incorrect validation on the Iroha side. #2664 should fix this issue without any additional work. Therefore we aren't going to invest more time in it.

How to reproduce the issue:
1. Take [this test](https://github.com/soramitsu/iroha2-tools/blob/master/csv-data-migration)
2. Simplify [this example](https://github.com/soramitsu/iroha2-tools/blob/master/csv-data-migration/src/test/resources/example.csv) data and leave only these rows:
```csv
_id,date_received,phonenumber,originating_country_code,origination,termination,dial_length,range_start,range_end,number_of_numbers,operator,number_type,identity_key,confidence_level,status
10465,"2022-06-20 00:00:00",355682607,355,AL,HU,8,35568260700,35568260799,100,"ALBtelecom Sh.a.(F)",Unallocated,0,1,1
10628,"2022-06-20 00:00:00",355682607,355,AL,HU,8,35568260700,35568260799,100,"ALBtelecom Sh.a.(F)",Unallocated,0,1,1

```
3. Try to run the test, and you should get panic on the Sumeragi main loop:
```
The application panicked (crashed).
Message:  Failed to apply block on WSV. This is absolutely not acceptable.: 
   0: Repetition

Location:
   core/src/wsv.rs:259

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup a tracing-error ErrorLayer and the semver versions are compatible
Location: core/src/sumeragi/main_loop.rs:295
```

What's going on with this test? The Iroha marks both transactions as valid because it validates them on isolated WSVs that don't affect each other. Still, these transactions contain instructions that affect each other (both transactions have the instruction that registers asset definition with name +35568260700-+35568260799#contribution). After the incorrect validation, these transactions fall into the main loop where Sumeragi tries to apply them and get crashes.
