### ISSUE TITLE
[documentation] Fix doc test `filter_derive`

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#2604]
### Documentation URL(s)

_coming soon_

### Description

- [ ] Un-ignore the doc test `id_derive`
- [ ] Fix and un-ignore the doc test `filter_derive`

_commit SHA is coming soon_

```bash
cargo test --doc -p iroha_data_model_derive filter_derive -- --ignored
```

![image](https://user-images.githubusercontent.com/49983831/183857899-1e01cbd9-1868-42d1-b7fb-481f25c9f564.png)

### Your suggestions

No idea at the moment.

**Comment by ilchu** [comment]
As it's my code, I believe that these tests should be ignored.

Their point is to show generated structures based on some example from `data_model`, but as that crate can't be a dependency of its own `derive` crate (otherwise we introduce a cycle), the structs used in the example such as `AssetDefinitionsMap` can't be imported. And even if they could be, the point is to give an example of generated code, and there's no invariant being checked -- the whole example is for reference purposes.

I'll fix it either together with my #2602 PR or split it off, and close these issues then.
