### ISSUE TITLE
Consider making format changes directly to a PR's contents

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#2674]
https://github.com/marketplace/actions/github-action-for-committing-changes-to-a-repository 

Would allow us to make programmatic changes to the PR contents. This should be useful when dealing with formatting changes, and in cases where we simply need to re-generate a new file. 

So my question is, should we consider this, and are there any special considerations, 

### Applications
- [ ] format check  ⇒automatic format
- [ ] genesis check ⇒ Automatic genesis creation
- [ ] clippy lints ⇒ clippy fix for trivial changes. 
- [ ] doc check ⇒ doc generate
- [ ] swarm check ⇒ update compose files

**Comment by 6r1d** [comment]
> should we consider this

Yes

> are there any special considerations

[The code](https://github.com/devops-infra/action-commit-push) is shell-based, so I don't expect it to overcomplicate anything extensively. It would probably be relatively easy to modify as well.

**Comment by BAStos525** [comment]
Actually we already use this Action to update `Cargo.toml` dependencies for [longevity script](https://github.com/soramitsu/iroha2-longevity-load-rs/blob/631ae48b2ed01a35f2fdbb34986433a65da35600/.github/workflows/update-dependencies.yaml#L51). I guess it could be useful for iroha2 CI as well as guys mentioned earlier.

**Comment by 0x009922** [comment]
Consider this:

- https://github.com/hyperledger/iroha-2-docs/pull/52

In Iroha 2 Documentation project we wanted to apply formatting automatically and push it back to the PR. It turned out to be a bad idea, primarily because it cannot work if a PR is created from a fork - an action couldn't push into it.

So, I don't think that this issue is a good idea.

However, it is very important to have an automated check that the generated files (schema, api reference, config reference, etc) are up to date.

**Comment by mversic** [comment]
we don't want to pollute history with format changes
