### ISSUE TITLE
Optimize usecase of `fn(self) -> Self`

### ISSUE THREAD

**Issue by Erigara** [hyperledger/iroha#2676]
Initially we had optimization of case when function consume and return self. 

This optimization was created with assumption that every structure passed as pointer into FFI, which not hold for non-opaque structures and transparent structures with non-opaque inner field.

We should explore possible ways to turn on this optimization depending on struct type, but it seems like we can't decide type of structure from just looking on structure `impl` block. 

[Original discussion](https://github.com/hyperledger/iroha/pull/2644#issuecomment-1230366129).

**Comment by mversic** [comment]
The situation described here is something like the following:
```rs
#[FfiType]
struct S(Option<u32>);

#[ffi_export]
impl S {
    fn set_field(mut self, a: u32) -> Self {
        self.0 = Some(a);
        self
    }
}
```

which currently produces:
```rs
extern fn S__set_field(handle: *mut S, a: u32, output: *mut *mut S) {
    // ...
}
```
but should better be:
```rs
extern fn S__set_field(handle: *mut S, a: u32) {
    // ...
}
```
where `handle` is taken as a reference instead of transferring and returning ownership

**Comment by mversic** [comment]
Given a method `fn builder([mut] self, ...) -> Self`, this can be done by replacing it with `fn builder(&mut self, ...)` and then generating FFI function out of it for any type (opaque or not). Or in a similar fashion. The benefit is that the same allocation is reused instead of dropping the first and writing the result in the `output` allocation provided by the user

We can even expand this pattern so that we convert even `fn builder(..., [mut] self, ...) -> Self` with arguments preceding `self`

The question is do we want to make this function conversion or not. I would only do this for `ffi_export` on `impl` blocks where `Self` is received and returned from a method. I wouldn't do it on freestanding functions e.g. `fn primitive(a: u32) -> u32`
