### ISSUE TITLE
Fix base coverage

### ISSUE THREAD

**Issue by s8sato** [hyperledger/iroha#2781]
> S. Sato, [2022/09/16 17:33]
> I think coverage should be fixed to be compared with the target branch, otherwise PRs can't be evaluated with its contribution to coverage
> 
> S. Sato, [2022/09/16 17:41]
> [In reply to S. Sato]
> I remember we made an optimizing change to the coverage upload. As long as it is not working properly, it would make sense to revert

**Comment by BAStos525** [comment]
Well, it seems as #2798 didn't help. Perhaps the problem might be in `Codecov` bot instead of `codecov report upload` GH Action.
We could learn [this page](https://docs.codecov.com/docs/comparing-commits) and play with settings in `codecov.yml`.

**Comment by adaagava** [comment]
Works now https://app.codecov.io/github/hyperledger/iroha/commits

**Comment by BAStos525** [comment]
Hmm, we expect to see the correct Coverage changes reported, but it looks like still [wrong coverage diff calculation](https://github.com/hyperledger/iroha/pull/3014#issuecomment-1352644640) within Codecov Coverage bot. Moreover, [Codecov check is failed](https://github.com/hyperledger/iroha/pull/3014/checks?check_run_id=10109123439) as well due to coverage asset decreasing.

**Comment by BAStos525** [comment]
It was switched to Coveralls instead of Codecov in [PR#3513](https://github.com/hyperledger/iroha/pull/3513).
