### ISSUE TITLE
[suggestion] Make a query builder and remove the boilerplate `request_with_*` methods

### ISSUE THREAD

**Issue by pesterev** [hyperledger/iroha#3124]
### Feature request

My suggestion is to make a builder and to get rid of these `Client`'s `request_with_*` methods.

### Motivation

We have many boilerplate `Client`'s query methods. 

### Who can help?

@appetrosyan @pesterev

**Comment by appetrosyan** [comment]
Good idea. Let's make sure we cover all of the patterns in the code.

**Comment by pesterev** [comment]
Another suggestion is [to use "default parameters"](https://github.com/hyperledger/iroha/pull/3118#discussion_r1100064851).

**Comment by appetrosyan** [comment]
Personally, this is up for debate. The builder pattern is common-enough in our code base not to surprise new users. While in a vacuum I'd prefer having a struct and use the `..Default::default()` in a struct literal, because we already make good use of the builder pattern elsewhere it'd lead to less surprise.

**Comment by Erigara** [comment]
@appetrosyan @pesterev i don't insist on `..Default::default()`, i agree that we already have enough places where we use builders, so we can keep doing that. 
I just want to provide options for us to consider.
