### ISSUE TITLE
Log is always output

### ISSUE THREAD

**Issue by SasagawaHiroshi** [hyperledger/iroha#327]
I'm trying unit test for logger(core/utils/logger.cpp) in "develop branch". 
But log is output by the following program.

(program)
logger::setLogLevel(logger::LogLevel::Warning);
logger::info("test-module") << "message1";

(log output)
1494389856 INFO [test-module] message1

**Comment by motxx** [comment]
Thanks for your finding!

`detail::LOG_LEVEL` is set by `logger::setLogLevel()` but suppressing debug log won't work because `detail::LOG_LEVEL` is in the header file(`logger.hpp`).
https://github.com/hyperledger/iroha/blob/develop/core/utils/logger.hpp#L29-L36

It works correctly if `detail::LOG_LEVEL` and `void setLogLevel(LogLevel)` are moved to `logger.cpp`. 

```diff
--- a/core/utils/logger.hpp
+++ b/core/utils/logger.hpp
-namespace detail {
-static LogLevel LOG_LEVEL = LogLevel::Debug;
-}
-
-inline void setLogLevel(LogLevel lv) {
-  detail::LOG_LEVEL = lv;
-  spdlog::set_level((spdlog::level::level_enum)lv);
-}
+void setLogLevel(LogLevel);
```

```diff
--- a/core/utils/logger.cpp
+++ b/core/utils/logger.cpp
+namespace detail {
+LogLevel LOG_LEVEL = LogLevel::Debug;
+}
+
+void setLogLevel(LogLevel lv) {
+  detail::LOG_LEVEL = lv;
+  spdlog::set_level((spdlog::level::level_enum)lv);
+}
```

If possible, could you create PR for develop branch?

**Comment by SasagawaHiroshi** [comment]
OK! I'll try.
