### ISSUE TITLE
[suggestion] Make all permissions explicit

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3270]
### Feature request

I'd like Iroha 2 to remove all *implicit* permissions in favor of *explicit* ones.

## What I mean by *implicit*?

I mean all permissions which are not represented by *Permission Tokens*. As an exmaple of these permissions can be the ability to mint/burn/unergister asset if user has registered it.

## What I mean by *explicit*?

Permissions that are represented with *Permission Tokens*.

## What we can do?

We can completely replace *implicit* permissions with *explicit* ones.
For example when user registers new asset definition they gets a lot of permission tokens which give them power to burn/mint it and etc.

## Pros

Solves all problems described in **Motivation** section

## Cons

- ~~No idea what to do with `Revoke` called by user on them-self. Looks like it stil should be always possible (at least in the default *Permission Validators* configuration we provide) and that means, it should be another *implicit* permisssion~~ (see #3275 solution)
- We just removed *Permission Tokens* hardcoding and now we should bring them back, because i.e. creating asset definition should also provide a lot of permissions, so it should be implemented in `Register<AssetDefinition>` isi. Or we can implelment it in *Permission Validator*, but that would be strange

## Motivation

Current implementation with *implicit* permissions have the following problems:

- Requires additional code in *Permission Validators*. Example: `is_asset_creator()` usage in validators
- Users can't decline permissions they don't need. Example: asset definition creator want to prove that they won't be able to burn it from someone
- Implicit permissions are not so clear and expectable. Example: as @mversic [says here](https://github.com/hyperledger/iroha/pull/3106#discussion_r1114251794) we used to have redundant permission granting it test, because we forgot about implicit permissions
- As a follow up: hard to check for redundant tokens. Example: to make this possible we need to replicate the behaviour similar to additional code in *Permission Validators* but in another way, because in all `Grant` instructions we need to check this implicit conditions

### Who can help?

@arjentix, @mversic, @appetrosyan

**Comment by mversic** [comment]
while this makes for a much more clear design my concern is of the impact this will have on the account size. This concern could be alleviated by using a set of predefined roles?

**Comment by appetrosyan** [comment]
## Considerations

### 1: Communication

As of now, we use Permission tokens as extras to inform our users that regular permission validation will make an exception for a rule. We understand that there are some rules implicit to the permission validators, and that those rules don't need to be repeated every time. Just because you don't have an explicit permission doesn't mean that you're not allowed to do something. 

This is a sparse representation. It's economical with respect to both space used on the blockchain, and with respect to the user. Given that the representation is sparse users know that the permission tokens aren't the whole story, and that they need to consult the permission validator source code for the final source of truth. 

If you added an explicit permission token for everything, the users assume that the system already knows what they would and would not be allowed to do. And this, given that the permission validators can change their minds on a whim, means that it's much harder to sync what's communicated to the user, and what's actually going to happen. 

### 2: Storage

This is a minor point. In practice most graph visualisation libraries use a sparse representation even if they want to present a dense matrix. We could do something similar in the sense that the query that returns all permission tokens *can also* return the implicit permission tokens by running a dummy transaction through the permission validators and seeing which verdict was `Allow` and which was `Deny`. 

In practice this is not possible, because our `PermissionToken`s are parametric, and so you'd have to return either all the possible accounts or some wildcard. Given that permission validators are turing complete, we can't even guarantee that the validator will return anything in a finite time. 

And if we just store the tokens you open yet another can of worms. 

### 3: Sync

The permission validator is the one thing that determines if a transaction passes or not. It is the _final source of truth_, and a permission token cannot be guaranteed to do anything. Referring to the same issue as with **# Communication**, in order to ensure that when an account has a permission token we should elaborate what that means. 

It could so happen that having a permission token means that you can do something _once only._ How do you differentiate permission tokens that have an expiry date, or some complex background logic from other tokens which seem to be permanent. Adding extra data as in #3275 is _not_ the solution, I'm afraid. 

### 4: Runtime upgrade

If we grant all explicit permission tokens in genesis based on some static analysis of the permission validator (which is extra unnecessary work), you can _also_ grant the permission tokens regularly by an admin account. Now imagine that after the upgrade permissions which were implicitly allowed are not implicitly denied. How do you differentiate which ones were granted automatically and which were added explicitly, without going through the entire blockchain history. 

More importantly, if the explicit permission wasn't granted because someone already had an implicit permission how do you globally revoke a permission. 

One issue that cropped up is _what if an account has an implicit permission and someone else grants it explicitly_? Well, the answer is, if the implicit permission got revoked by a runtime upgrade the explicit permission remains. 

## Conclusion

This is more likely a consideration for the RFC. We need to consider if we want to do it, and if we do, all of the above edge cases should be handled.
