### ISSUE TITLE
[bug]: Investigate spurious build failures

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3311]
`cargo build` from workspace root works. `cargo build` from dir does not. 

_Originally posted by @mversic in https://github.com/hyperledger/iroha/pull/3077#discussion_r1136983239_

**Comment by mversic** [comment]
so it seems that when built from workspace `cargo` unifies all features. For instance if you go to a `client` or `client_cli`and rely on API exposed from the `data_model::transparent_api` the build will be successful if run from workspace root, but will fail if run from the `client` or `client_cli` directory. 

Expected behavior is that build should fail in all cases because `data_model::transparent_api` is not enabled by the `client` or `client_cli` crates

**Comment by Arjentix** [comment]
To reproduce:

1. `cargo check`: works (not expected)
2. `cargo run --bin iroha_client_cli`: works (not expected)
3. `cargo build --package iroha_client_cli`: doesn't work (that's expeced because we really have an error in the code)

**Comment by mversic** [comment]
related to https://github.com/rust-lang/cargo/issues/4463

**Comment by mversic** [comment]
related to #3423

**Comment by mversic** [comment]
related to #3423
