### ISSUE TITLE
Limit runtime evaluation of recusive structures

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3347]
Currently we have limits such as number of transactions or wasm blob size. However, I don't believe that we have any limit for `EvaluatesTo`/`Expression` evaluation. This means Iroha is susceptible to DOS attack through unlimited expression evaluation in queries, instructions, `SignatureCheckCondition`, etc. This limit should be applied both to `http` requests and `wasm`

The same might be said for event filters or predicates or other recursive structures provided by user

**Comment by appetrosyan** [comment]
Well, actually #2409 would preclude infinite recursion. DoS can be controlled by a gas price mechanism, where computational resources are cut as soon as the fuel limit is reached, and fuel is consumed proportionately to the computation. 

Reason this is better, is because if the limit is $1000$ recursive evals, I will find ways to submit an instruction which has $999$ and still clog up the system. At the same time there might be legitimate use cases where $999$ is the right recursion depth.  There should be both discouragement for spam, but also an allowance. 

Deciding if infinite recursion would halt is the so-called iota combinator problem which is unsolvable by a Turing machine, because of the Church-Turing thesis.

**Comment by mversic** [comment]
if we're going to evaluate expressions only in Executor this might not be relevant anymore

**Comment by mversic** [comment]
expression were removed
