### ISSUE TITLE
Apply genesis transactions directly on WSV, not on a Clone

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3382]
Currently we have redundant clonning of WSV when applying genesis transactions. Instead we should apply it on real WSV and panic if transaction fails

**Comment by mversic** [comment]
referenced [here](https://github.com/hyperledger/iroha/pull/3329/files#r1162760915).

I think the scope of this ticket is incorrect. I don't consider this a performance issue because it only applies for genesis and creating another branching would just unnecessarily complicate things. What I am advocating is that we should panic when verifying genesis if it has even one invalid transaction. There is no point in allowing invalid transactions in genesis.

**Comment by mversic** [comment]
@Arjentix @Erigara is this still relevant? if not, please close the ticket

**Comment by mversic** [comment]
ping @Arjentix

**Comment by Arjentix** [comment]
Yes, still relevant, I just checked `sumeragi_init_commit_genesis()`.

Also I vote not for panic on invalid genesis, but a proper error hadling. I don't think that in a good program user should be able to trigger panic by submitting wrong config

**Comment by mversic** [comment]
@Erigara I think this can be closed?

**Comment by Erigara** [comment]
@mversic yes, i think

**Comment by mversic** [comment]
not relevant anymore
