### ISSUE TITLE
Investigate how `wasmtime` caching affects performance

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#3410]
In #3400 I have discovered that `wasmtime` caching affects our integration tests by improving start-up time, i.e. wait time until genesis is committed. This is related to the time required to compile `validator` module in `genesis.json`. It is unclear why this is so but my suspicion at the time was that this is due to integration tests sharing the same cache. It should be seen if this will hold true after we migrate to python-based integration tests.

In the scope of this ticket it should be investigated does `wasmtime` caching affect live system performance. Does `Iroha` benefit from this cache since there is no recompilation of modules?

**Comment by Erigara** [comment]
After some investigation it was discovered that "since there is no recompilation of modules" assumption is not entirely correct.

1) In case of peer restart modules will be recompiled and cache will save some time.
2) Executable inside transaction can be wasm smart-contract, in case of popular (actively reused) smart-contracts caching will save time recompiling modules.
