### ISSUE TITLE
[refactor] Streamline naming convention

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3436]
### Feature request

We need to clarify the naming convention of the Iroha 2 objects. I propose the following: 
- `Domain`
- `Account`
- `Asset` that is `rose##alice@wonderland` to be renamed `Wallet`. 
- `AssetDefinition` to be renamed `AssetType`

### Motivation

Confused users and confused developers have complained about our terminology. This will fix it somewhat.

**Comment by mversic** [comment]
I'm wondering why do we need/have domains? I see it's possible to register(or transfer) `AssetDefinition` by an account form another domain, so it's not isolation.

[This](https://support.metamask.io/hc/en-us/articles/13466457757211-What-s-the-difference-between-a-wallet-and-an-account-) is what `MetaMask` has to say on `Account` vs `Wallet`. If we take the definition of a `wallet` as a digital entity that stores keys then it seems to be synonymous with `Account`. We could rename `Account::assets` field into `Account::wallet` because in our case `Account` is something more then a wallet, but they seem to be a related concept

I would propose the following:
- `Domain`
- `Account`
- `Asset` that is `rose##alice@wonderland` to be renamed `Balance`.
- `AssetDefinition` to be renamed `Asset`

**Comment by QuentinI** [comment]
I agree that `Wallet` sounds more like a collection of assets, i.e. what is currently `Account`, not `Asset`. I feel like `Account` is fine as it is. Furthermore, I agree on `AssetDefinition` -> `Asset` suggestion. `AssetType` feels more suited for distinguishing between e.g. Quantity/Store assets that between assets themselves.
As for `Asset` -> `Balance` suggestion, this doesn't feel quite right if you consider NFTs for example. Also, while for something in `Account` this naming make sense, `Mint<Balance>` doesn't sound intuitive. `Amount` sounds like something that can both be minted and belong to an account, although it still doesn't seem quite right for a Store or an NFT.
Overall @mversic's suggestion makes the most sense to me, excluding `Asset` -> `Balance`, instead of which I propose `Asset` -> `Amount` or something similar.

**Comment by appetrosyan** [comment]
I personally like the nomenclature we have right now. However, users have complained that they can't easily map the concepts from other blockchains onto what we have. 

Re: `Wallet` while from a pure English language standpoint you are correct, blockchain parlance uses `Wallet`s in multiple contexts. It can mean something that stores keys. It can mean the application that allows you to manage your assets. It can also mean the collection of assets that is accessible through the key. 

Re: interaction with `Mint`. 
- `Mint<Asset>` is lexically sound, but vague. Are you minting it to a specific account? Abstract nothingness? Everyone's wallets all at once? Can `Asset` be an NFT? And why, if an NFT is Minted in Ethereum, is it not `Mint`-ed in Iroha. 
- `Mint<Balance>` is precise, but lexically unusual. This tells you that you are in fact increasing the amount of assets of a specific account. The unfortunate implication is that the `Balance` can be negative. Ours cannot. 
- `Mint<Wallet>` is less precise and less unusual, given the blockchain jargon. It tells you that you are minting to a specific wallet: a bucket that holds assets. Which is why I prefer this approach if any. 

We also have to remember that we can change `Mint` to another word. 

`Add<Balance>` or `Increment<Balance>` sound much better. `Balance` still implies signed-ness, though and this can introduce ambiguities: why do we `Increment<PublicKey>` and why do we `Register<Peer>` instead of `Add<Peer>`. 

A surgical adjustment would be to say `MintTo<Wallet>` which also tracks with our usage of `MintTo<Trigger>`, and disambiguates the meaning of the object in angle brackets. 

However, Given what was voiced, I think that we ought to keep the old nomenclature and just explain it better in the docs.

**Comment by QuentinI** [comment]
> I personally like the nomenclature we have right now. However, users have complained that they can't easily map the concepts from other blockchains onto what we have.

I feel like the biggest problem is `Asset`/`AssetDefinition` distinction, which even some developers, including me, have gotten confused by.

> However, Given what was voiced, I think that we ought to keep the old nomenclature and just explain it better in the docs.

After reading your comment, I agree. Perfect nomenclature seems out of reach, and given amount of work to change one confusing nomenclature to another possibly-slightly-less-confusing doesn't seem worth it.

**Comment by appetrosyan** [comment]
After discussion we reached no consensus, and will keep the old convention for compatibility.
