### ISSUE TITLE
[security] Parameters in the `wsv` are active in `sumeragi` with delay

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3469]
This creates a narrow window when the parameter is set in the `wsv` and not active in the consensus. I'd highly recommend adding it to the `troubleshooting section` in the docs @6r1d. or @outoftardis

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3457#discussion_r1186836951_

**Comment by mversic** [comment]
@Erigara please verify this

**Comment by Erigara** [comment]
After checking i think this shouldn't be the issue:

1. `Sumeragi` isn't exposed to outside world, other modules deal with handle to it => so it's not possible to access it's parameters
2. Window between updating `Sumaragi` and `State` parameters can't affect consensus because when new block is processed both `Sumeragi` and `State` parameters already updated.
