### ISSUE TITLE
[suggestion] Trace configuration parameters resolution

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#3502]
### Feature request

When something goes wrong in configuration, it is essential to trace where a particular parameter data came from. E.g. you have some parameters specified in ENV, some in JSON, and when you get an error, you want to know in which place you should fix it. 

It might be also useful to log the resolution process on TRACE/DEBUG level so you can inspect what data is loaded from where, what is overwritten by what, etc.

And of course, when you have a configuration error, you should know the field location as precise as possible:

- #3470

**Comment by appetrosyan** [comment]
Best thing we can do is add `println` statements whenever we override one parameter with another. 

The reason why this couldn't be `iroha_logger::debug!` for example is because logging is also controlled by the configuration and might not be initialised at all times. Plus this happens once in the early init, so there's not many reasons why `prinltn` would be a bad idea.

**Comment by 0x009922** [comment]
Closed by #4456
