### ISSUE TITLE
[suggestion] Allow querying for original WASM blobs/sources 

### ISSUE THREAD

**Issue by QuentinI** [hyperledger/iroha#3516]
### Feature request

Provide an API to match WASM blobs as stored on blockchain with `LoadedModules` as they are in the WSV.
As a way more ambitious goal - figure out building WASM contracts reproducibly and do that on the node, allowing to trace WASM back to the source code.

### Motivation

Trivial motivation for me: needed by iroha-squash to report which contract is which when squashing blockstore.
Overall motivation -  SCs would be easier to inspect in public blockchain use cases.

**Comment by mversic** [comment]
as I mentioned [here](https://github.com/hyperledger/iroha/pull/3517#issuecomment-1558838514) returning compiled wasm was an oversight. We should change the API of `FindTriggerXXX` queries to return whatever user has submitted, not our internal representation

**Comment by mversic** [comment]
If we go with this suggestion (and I strongly think we should), I don't see how we can have queries that return both optimized or original wasm blob. We should make a choice what these `FindTriggerXXX` queries should return.

@Mingela do you mind us changing the behavior of these queries to return original wasm smart contract as was submitted (and as is recorded on the blockchain). Was there a reason why you would need a compiled one? How would you use it?

**Comment by Arjentix** [comment]
We still need optimized WASM to be able to locally debug wasm if something goes wrong.

As I mentioned before, our queries report with the current world view. And world never contains original wasm, it always stores the optimized version.

I think it should be some different query of even different *kind* of query. And I don't think it was an oversight.

**Comment by mversic** [comment]
> As I mentioned before, our queries report with the current world view. And world never contains original wasm, it always stores the optimized version.

world state view is not a concept that end user should ever hear about. Justifying API decisions based on internal representation (and wsv is an IR) of data is wrong IMO and opens a whole new can of worms.

> And I don't think it was an oversight

ok, let's not call it that

Let me make a summary, trigger queries should return original wasm because:
1. this is what user expects to be returned (needing an optimized wasm, is for the power user, not common user)
2. returning optimized wasm exposes our internal representation (it tells everyone that we're using `wasmtime`)
3. optimized wasm representation is not stable. This ties our public facing API to a concrete implementation of wasm VM (`wasmtime` ATM). Not only that, it also ties public API to a specific version of `wasmtime` since even that is not stable
4. different Iroha nodes could be running different versions of `wasmtime`. This itself makes returning optimized wasm almost entirely useless 
5. you will still be able to debug, even more so with original wasm

As for debugging, I wonder who is debugging what? Is it:
1. we as devs debugging our implementation of Iroha during development? - then we should use some feature flag for these queries. We don't want this API to leak into public
2. users debugging their smart contract implementation? - then I don't understand why would they want a compiled wasm blob? they can take the original wasm blob and run it against **any** version of `wasmtime`, not only the one used by Iroha node. There is no point in running it against a specific version of `wasmtime` since `wasmtime` guarantees that it can be run/compiled on/with any version of `wasmtime`. Unless they're debugging Iroha (covered by 1st point) or `wasmtime` itself (which is not our problem) the user will never care about the specific version of `wasmtime`

**Comment by QuentinI** [comment]
Strongly agree with @mversic on what trigger queries should do.
As for internal representation, I'd say it can still be useful to be able to ask for that under some sort of `DebugXXX`  family of queries that wouldn't have any stability guarantees for output. I don't think we need to try to hide IR further, and if someone chooses to rely on `Debug-` query behavior for production code it won't really be our problem

**Comment by 0x009922** [comment]
> Justifying API decisions based on internal representation (and wsv is an IR) of data is wrong IMO and opens a whole new can of worms.

I agree.

Something that is not clear to me: why do we need to expose internal WASM representation through public facing API? If a developer needs to get access to internal representation, they might work with Kura directly, right?

**Comment by Mingela** [comment]
> @Mingela do you mind us changing the behavior of these queries to return original wasm smart contract as was submitted (and as is recorded on the blockchain). Was there a reason why you would need a compiled one? How would you use it?

No, I don't. I totally support your view and conclusion
