### ISSUE TITLE
[discussion] Refactor WSV to remove God Object anti-pattern

### ISSUE THREAD

**Issue by Arjentix** [hyperledger/iroha#3560]
This is a ticket for discussion about our `WorldStateView` struct.

Some of us think that it's too big and is *[Gob Object](https://en.wikipedia.org/wiki/God_object)*.

Some of us think there is no problem there.

**Comment by mversic** [comment]
> Some of us think there is no problem there.

For the record this was me. Let me make it clear, I do think that __God object__ is a bad pattern to follow and yes __WSV__ looks a lot like a __God object__. 

The discussion I started [here](https://github.com/hyperledger/iroha/pull/3477#discussion_r1213887996) only superficially looks like it is a discussion about __God object__. However, using `wsv.validator_view().clone().validate(tx)` instead of `wsv.validate(tx)`, doesn't mean that `wsv` will stop being a __God object__ because the access to the validator is still given only through `wsv`. IMO it is perfectly fine to do the suggested replacement

How to make `wsv` not be a __God object__ should still be worth investigating

**Comment by appetrosyan** [comment]
For the record, the problem of a God object has to be understood. 

The issue we have is not that we have a location in memory that stores the entire context, nor that the context is big. If we were CPU engineers the entirety of RAM and NVRAM would be our god object, and while you could get into a debate over the mechanics, there's not a lot of a choice there. 

The issue here is that the God object, the `wsv` entails that **any one modification** of either one part of it can potentially affect everything else. In other words, changing metadata for one object can potentially change how `smartcontracts` behave globally. As you can probably tell, this is not a problem that is solvable with any one solution. 

It is possible for example, to allow domain-scoped modifications. Arguably, you'd still have to go through `wsv` but you're a bit more granular, so you're talking to a piece of a God object rather than a full god object. This is not viable on all levels of abstraction without some form of Polymorphism which would be a huge headache to implement. On the plus side, the borrow checker and lack of interior mutability allow a more granular polymorphic set of instructions to affect smaller objects and prevent data races. The negative would be an almost exponential penalty on binary size. **I honestly don't think that fighting this anti-pattern** is worth the time, money and effort. 

It's not just about cleaning up the code, it's about providing the user the guarantee which is simply impossible to do given our imperative smartcontracts, and lack of compile-level access control. We can't know which entities can affect which data, because by default every account can affect everything on the blockchain. The simple truth is that *in a monolithic structure, the state of the system is also a monolith*. This has benefits. The logic on-chain can be arbitrarily complex. Given the niche we're trying to occupy and the architectural decisions which were made long before I was even a mid-level engineer working on the project suggest that the God object is the right approach.

**Comment by appetrosyan** [comment]
Voted 6/7 in favour of not prioritising this issue. 

If a suitable decoupling methodology is presented we should re-open.
