### ISSUE TITLE
[refactor] Consider inlining the implementation of the `DefaultValidator`

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha#3765]
This file is a little confusing. A while ago I fully expected to find the entire validator here as a reference implementation. 

Why did you decide to make this a separate crate, but also not to provide the actual logic inside of it? Wouldn't it make more sense to inline at least the top level functions instead of just having one line per function?

_Originally posted by @appetrosyan in https://github.com/hyperledger/iroha/pull/3723#discussion_r1278091675_
            

## Proposed solution

Inline the logic of the `DefaultValidator` into the place that most users would expect to find it.

**Comment by Arjentix** [comment]
I agree with that, however I think @mversic had some reasons to do so. The main problem AFAIK was orphan rule for our traits

**Comment by mversic** [comment]
the problem we have is that we want the following:
* blank validator - where everything passes. This we get with `Validate` trait where all methods just `pass`
* default validator - this is a validator that implements `Validate` and overrides some of its methods. This is `DefaultValidator` in codebase

Both `Validate` and `DefaultValidator` are defined in the `wasm/validator` library. When a user wants to make their own validator they create their own project and import dependencies from `wasm/validator`. They don't go and use `default_validator` crate. This crate is only for our internal purposes because we need a validator for testing the `DefaultValidator`. What this crate does is it emulates what the user would do, like an example repository.

If this creates confusion. I wouldn't mind if we moved this crate into `client/tests` or rename it into `test_validator` or something along those lines. Additional problem is that I think `kagami` also depends on `default_validator` crate to generate the `validator.wasm`
