### ISSUE TITLE
[documentation] Iroha-SDK release interdependency

### ISSUE THREAD

**Issue by Mingela** [hyperledger/iroha#3865]
## Documentation URL(s)

https://github.com/hyperledger/iroha/blob/iroha2-dev/docs/source/release_procedure.org

**Comment by AlexStroke** [comment]
Let's create a table that outlines the SDK update process and its relationship to Iroha releases something like below. This would enhance transparency and clarify tasks and responsibilities at each stage.

Just for example:

| Stage  | Who Does It                    | What To Do                                                                                     |
|-------|-------------------------|---------------------------------------------------------------------------------------------------|
| 1     | Project Manager         | Conduct a pre-release sync meeting.                                                                |
| 2     | Tech Lead          | Appraise all present of main API-breaking changes requiring attention.                            |
| 3     | Tech Lead          | Walk through the differential between `iroha2-stable` and `iroha2-dev` branches.                    |
| 4     | Core Team & SDK Teams   | Sign off on a release and announce the opening of the release window.                              |
| 5     | DevOps                  | Release a `nightly` docker container through the continuous delivery system.                       |
| 6     | Tech Lead          | Create a Pull Request from `iroha2-dev` to `iroha2-stable` with the release checklist.             |
| 7     | SDK Engineers           | Allocate resources for SDK updating.                                                               |
| 8     | SDK Engineers           | Update SDKs (Kotlin/Java, JS/TS, Python, Swift) for compatibility with upcoming Iroha release.      |
| 9     | Project Manager         | Confirm that SDKs are updated and functioning; otherwise, move to an internal release.             |
| 10    | QA Engineers            | Update Iroha-related tools like iroha-squash for new SDK versions.                                 |
| 11    | Core Team Developer               | Review and tick off points on the release checklist related to SDK updates.                         |
| 12    | Core Team Developer               | Report any major breakages in the relevant chat and respond to inquiries about changes.            |
| 13    | Core Team Developer               | Produce standard packages (Nix, AppImage, .deb, .rpm) and upload to relevant locations.            |
| 14    | Project Manager         | Form a proper GitHub release and provide links in relevant chat.                                   |
| 15    | Tech Lead                | Close the release window upon completing the release checklist.                                    |

**Comment by Mingela** [comment]
@dmitrivenger should we close that?

**Comment by Mingela** [comment]
closing in favor of https://github.com/hyperledger/iroha-rfcs/pull/10
