### ISSUE TITLE
Fix client build

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4014]
Client cannot be built with `cargo build -p iroha_client` again due to recent changes in #3929

**Comment by timofeevmd** [comment]
what is done

`iroha git:(iroha2-dev) cargo build -p iroha_client

 Compiling iroha_wasm_builder v2.0.0-pre-rc.20 (/Users/michaeltimofeev/Documents/projects/iroha/wasm_builder)
   Compiling iroha_client v2.0.0-pre-rc.20 (/Users/michaeltimofeev/Documents/projects/iroha/client)
error: failed to run custom build command for `iroha_client v2.0.0-pre-rc.20 (/Users/michaeltimofeev/Documents/projects/iroha/client)`

Caused by:
  process didn't exit successfully: `/Users/michaeltimofeev/Documents/projects/iroha/target/debug/build/iroha_client-3d7b98df93d4a098/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=tests/integration/smartcontracts

  --- stderr
  Error: Failed to check the smartcontract at path: /Users/michaeltimofeev/Documents/projects/iroha/client/tests/integration/smartcontracts

  Caused by:
      `cargo check` returned non zero exit code (exit status: 101). Stderr:
      warning: /Users/michaeltimofeev/Documents/projects/iroha/schema/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

      consider passing `-Zlints` to enable this feature.
      warning: /Users/michaeltimofeev/Documents/projects/iroha/smart_contract/trigger/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

      consider passing `-Zlints` to enable this feature.
      warning: /Users/michaeltimofeev/Documents/projects/iroha/smart_contract/executor/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

`

`
 iroha git:(iroha2-dev) cargo +nightly-2022-12-22 build -p iroha_client_cli

 Compiling proc-macro-utils v0.8.0
   Compiling rustversion v1.0.14
   Compiling percent-encoding v2.3.0
   Compiling form_urlencoded v1.2.0
   Compiling manyhow-macros v0.8.1
error[E0658]: use of unstable library feature 'is_some_and'
   --> /Users/michaeltimofeev/.cargo/registry/src/github.com-1ecc6299db9ec823/manyhow-macros-0.8.1/src/lib.rs:283:33
    |
283 |             path.pop().as_ref().is_some_and(TokenTreePunct::is_semi),
    |                                 ^^^^^^^^^^^
    |
    = note: see issue #93050 <https://github.com/rust-lang/rust/issues/93050> for more information
    = help: add `#![feature(is_some_and)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `manyhow-macros` due to previous error
warning: build failed, waiting for other jobs to finish...

`
