### ISSUE TITLE
Target `iroha2-dev` branch for Coveralls

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4131]
our tests coverage should be compared against the `iroha2-dev` branch, not `iroha2-stable`. 

### Concerns
I was told that we target `iroha2-dev` branch because of computational resource concerns since target branch will have to be recomputed every time in case of `iroha2-dev`. If possible we should reuse latest build of `iroha2-dev` branch and share it among all active PRs so as to alleviate this a little bit. How big of a deal is to recompute target branch coverage?

**Comment by BAStos525** [comment]
We can't select the target branch manually since coverall detects only the default repo branch that is `main`. But [PRs against other base branches](https://coveralls.io/builds/64446950) are possible and we see them. The problem that it tries to compare every new PR against [the very old merger PR from 30Th June](https://coveralls.io/builds/61066259). It's weird because we had a similar issue with `Codecov`. And when I tied to cancel this old build, it went to the error. By the way, I have changed a couple of setting in Coverall and re-cached it. Let's watch if smth could change or we wiill nee to continue to investigate the problem.

**Comment by BAStos525** [comment]
I think I catch the problem: Coveralls compare each run with the correct iroha2-dev branch base commit, but for every new commit (run) withing the PR it creates the new job that doesn't know about the previous one PR head branch commit. So, we can't determine the summarized diff between head and base commits and as a result, we don't receive the Coveralls PR comment. May be it caused either by PR from fork or force-pushed commit or that i2-dev branch if not a default branch.

I suggest to try `Covecov` again. @mversic

**Comment by BAStos525** [comment]
If we take any PR, i.e. this one (https://github.com/hyperledger/iroha/pull/4053)
Then go to check and find coverage/coveralls (pull_request)  and click on details that should open Coveralls page. We see COMMIT MESSAGE Merge ef05a9c42 into 85d03b75e. Actual head and base commit SHA.
The problem here that it doesn't give the proper PR comments. I guess due to default branch thing or smth else:

**Comment by BAStos525** [comment]
I am pleasantly surprised that `coveralls` has started to send PR comments with coverage info. [Example](https://github.com/hyperledger/iroha/pull/4284#issuecomment-1947666529).
Also it seems that PR head commit is compared with the latest base iroha2-dev branch commit.
Can we resolve this issue? @mversic

**Comment by BAStos525** [comment]
I think it works now for our luck.
