### ISSUE TITLE
Minimal major configuration overhaul

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4161]
## Description

_Part of the RFC: https://github.com/hyperledger/iroha/issues/2585_

After making semi-minor changes to the config and CLI, I think it is possible to make a major step in Configuration Overhaul. In this issue I describe how I see this next major step.

At the very least it should match with the configuration reference (https://github.com/hyperledger/iroha-2-docs/pull/397), which I will enhance at the same time.

### Planned changes

- Drop JSON/JSON5 support for the configuration. Use TOML exclusively.
- Rename and restructure parameters, re-think ENV variables
- Support `extends` mechanism for easy configuration composition
- Move all parsing and validation logic into `iroha_config`, clearly distinguishing user-provided config from the parsed one
- Implement configuration tracing mechanism
- Move chain-wide parameters into a separate section until it is moved from the config entirely: https://github.com/hyperledger/iroha/issues/4028
- Perhaps, remove complex JSON values from ENV entirely: leave this space for primitives only
- Perhaps, use `miette` for comprehensive error reports

### Goals in mind

Since there will be a lot of boilerplate, it makes sense to continue development of project soukousei which will provide a generic way to work with configuration. However, I think it would be too costly to bother about it right now. Instead I want to re-write `iroha_config` fully manually. Although there will be a lot of boilerplate, the process will be streamlined and focused on the final result from the start. Moreover, after manual implementation it will be clearer how to design `soukousei`.

Therefore:

- Re-write `iroha_config` fully manually, despite having a lot of boilerplate
- Write code while keeping in mind that boilerplate will be moved to the library
- Prioritise errors handling quality: collect as much info as possible, build comprehensive reports

**Comment by DCNick3** [comment]
re: `miette`: might also want to consider [`ariadne`](https://docs.rs/ariadne/latest/ariadne/), which is focused solely on formatting the output nicely without trying to cover the use-cases of `thiserror` which might or might not be meaningful.

What would also be nice to see diagnostics-wise is emission of _all_ validation errors in one go, so that the user would not have to re-try launching iroha after fixing errors one-by-one and could instead see all (or, at least, most) of the validation problems right away. This can be achieved by using a error accumulator pattern, like was [done in iroha macros](https://github.com/hyperledger/iroha/blob/50ec2bc71821d81d05b2f4a7b9746c84166db025/ffi/derive/src/getset_gen.rs#L44) (the `emit!` macro doesn't fail the validation right away, allowing the execution to proceed and collect some more possible errors)

**Comment by 0x009922** [comment]
> might also want to consider [`ariadne`](https://docs.rs/ariadne/latest/ariadne/)

Thanks, will consider

> What would also be nice to see diagnostics-wise is emission of all validation errors in one go

For sure! It is one of the main points of the RFC.

**Comment by 0x009922** [comment]
Closed by #4239
