### ISSUE TITLE
Are genesis transaction signatures checked?

### ISSUE THREAD

**Issue by 0x009922** [hyperledger/iroha#4162]
> BTW, I am confused by both tests patching constructed `GenesisNetwork`. They are inserting plain instructions into the payload of a signed transaction. By doing so, AFAIK, they invalidate the signature of the transaction being computed using the previous payload. One test checks that Iroha validates genesis by providing an invalid permission token, but Iroha should not accept genesis because of its signatures I guess. Another test checks whether base64 triggers are handled fine. I don't why the second test passes.

_Originally posted by @0x009922 in https://github.com/hyperledger/iroha/pull/4153#discussion_r1432095800_

**Comment by DCNick3** [comment]
What I _think_ happens there: test_network starts the network with only a single peer and this single peer does not validate the genesis transactions, because they are a `SignedTransaction` and there should be no need to. However the `payload_mut` on `SignedTransaction` (and a public `payload` field of `SignedTransactionV1`, for that matter) circumvent this invariant.

I think that if the test network would have more than one peer, than these tests would not have worked, as to deserializa a `SignedTransaction` the signatures would have to be checked (at least I would hope so)
