### ISSUE TITLE
remove MST aggregation from iroha

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4229]
I think we should remove aggregation of MST signatures out of Iroha. Transaction signing should happen outside Iroha and only after all signatures have been collected should it be submitted to Iroha

This would also mean that we should remove `pending_transactions` endpoint

**Comment by 0x009922** [comment]
If this issue is closed as not planned and we decide not to remove `pending_transactions` endpoint, we should not forget to document it in the Torii reference.

**Comment by mversic** [comment]
also remove `hash_of_payload` from `SignedTransaction`

**Comment by s8sato** [comment]
I don't think it's too late to remove one feature after coming up with an alternative implementation.

I agree with stopping transactions pending in the queue because, if my memory is correct, at some point the queue became a performance bottleneck and its simplification might help.
However, collecting signatures outside Iroha seems to predict client-to-client communication or another server that presents transaction candidates and collects votes, about which I have no idea.

Instead, now that we have triggers, I think it is possible to implement multi-signature transaction proposal as a trigger registration, and approval for it as a voting instruction targeting the trigger. This approach is similar to [that of Polkadot](https://wiki.polkadot.network/docs/learn-account-multisig).
In this way,
- since candidates are committed, they will be visible via explorer as usual
- every transaction has one signature, which might save transaction size

Anyway, multi-signature is a common feature and we'd better consider alternatives
