### ISSUE TITLE
Fix `with_coverage`

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4488]
After merging #4414 `with_coverage` is failing

**Comment by AlexStroke** [comment]
![telegram-cloud-photo-size-2-5381943039976656869-y](https://github.com/hyperledger/iroha/assets/111361420/ccda2326-ecab-419a-bf74-aceb8507b355)
FYI This is 6th February using the new grcov report from Vasiliy

**Comment by s8sato** [comment]
As of 2cf50c0da `I2::Dev::Tests / with_coverage` is failing due to `-p iroha_client --test mod` (client/tests/integration/). It seems to happen with the following combination:

- `nightly-2024-04-18`
- `RUSTFLAGS="-C instrument-coverage"`
- `-p iroha_client --test mod`
  - not filtered out, because `#[cfg(not(coverage))]` is allowed by `cargo-llvm-cov` and does not work with `grcov`

I don't know the exact cause, but we can work around this. Just exclude the client integration tests in command without attributes
