### ISSUE TITLE
Open issues with merged PRs

### ISSUE THREAD

**Issue by nxsaken** [hyperledger/iroha#4587]
Sometimes I see open issues with merged PRs (pre-RC 21 references some of those, for example), some of them old. Are those cases of "forgot to close issue", or can there be some extra step that needs to happen before that? It's confusing when a release references an issue that's still open.

In general, should we just rely on GH's automatic closure of issues on associated PR merge?

**Comment by DCNick3** [comment]
I think those are mostly forgotten to close.

Due to the fact that for a long time iroha2 dev branch wasn't a default branch, GH's automatic closure didn't work (it only closes issues on merge to the default branch), so it should be quite common for PRs merged before the switch (happened to me too :sweat_smile:)

**Comment by nxsaken** [comment]
Thanks for clarifying! I'll be closing the issues as I find them
