### ISSUE TITLE
`decrypt_should_fail` spurious failure

### ISSUE THREAD

**Issue by mversic** [hyperledger/iroha#4994]
This test seems to fail spuriously:
```
---- encryption::chacha20poly1305::tests::decrypt_should_fail stdout ----
thread 'encryption::chacha20poly1305::tests::decrypt_should_fail' panicked at crypto/src/encryption/chacha20poly1305.rs:111:48:
called `Result::unwrap_err()` on an `Ok` value: [72, 101, 108, 108, 111, 32, 97, 110, 100, 32, 71, 111, 111, 100, 98, 121, 101, 33]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by DCNick3** [comment]
The problematic code is [here](https://github.com/hyperledger/iroha/blob/02479ce598854c35c106831e30f7223964703db3/crypto/src/encryption/chacha20poly1305.rs#L110). When `ciphertext[1]` is `0` the XOR doesn't do anything to the `ciphertext[0]` and the message turns out to be unexpectedly not corrupted.
