### ISSUE TITLE
Iroha logs 

### ISSUE THREAD

**Issue by developersteve** [hyperledger/iroha#504]
We've been testing the latest release (yay 0.95) and having a few issues that we are wanting to debug but cant seem to find any output logs. Are those stored anywhere or is there any output for errors?

**Comment by neewy** [comment]
Hi! Thanks for your interest to Iroha. Can tell me what would you like to debug so that we can tell you more?
Logs are not stored now, we log internal events in standard output. If you'd like to contribute, please check libs/logger/logger.cpp and its log() method - https://github.com/hyperledger/iroha/blob/master/libs/logger/logger.cpp#L47
Soon we will post an updated version of docker-based scripts, which will run multiple Iroha instances if this may help with your issues.

**Comment by developersteve** [comment]
@neewy having some issues getting it running in an env and more particular to being able to do transactions (registration of users is working just cant do a transaction). Thank you will check it out and see if i can help 😄

**Comment by neewy** [comment]
Hi Steve,
are you still having problems with transactions?

Please, check how to form a transaction here https://soramitsu.atlassian.net/wiki/spaces/IS/pages/8650823/External+Interface+Control+Document

**Comment by neewy** [comment]
also, please run Iroha node in docker container using script in develop branch: `sh scripts/run-iroha-dev.sh`

**Comment by neewy** [comment]
Please, reopen issue if it remains
