### ISSUE TITLE
Mention how to run tests in the documentation

### ISSUE THREAD

**Issue by sudheesh001** [hyperledger/iroha#558]
Currently the documentation does not make `How to test iroha` clear. I think it'd be great to add a line in the developer setup process to include the command to run the tests before further using `irohad` or `iroha-cli`

`cmake --build build --target test` should be the command to run the tests after building using 
`cmake -H. -Bbuild; cmake --build build -- -j4; `

**Comment by l4l** [comment]
We are actually using ctest, so you can use it instead
```
mkdir build && cd build
cmake .. && make # building
ctest . # running tests
```

But agree about the docs, thanks!

**Comment by neewy** [comment]
Thank you for being interested in Iroha project. It is a real need for us to keep level of documentation that may easily explain to newcomers how to accomplish basic things: building, testing project, etc.

We are going to start weekly meetings with developers since this sprint, so that we can talk directly about issues community members are having. It would be nice if you participate. 

For now, I will copy this snippet to GitHub pare here: https://github.com/hyperledger/iroha/wiki/How-to-test-Iroha

**Comment by neewy** [comment]
@sudheesh001 https://hyperledger.github.io/iroha-api/
