### ISSUE TITLE
Iroha documentation proposal

### ISSUE THREAD

**Issue by muratovv** [hyperledger/iroha#967]
The document describes the ideas of documentation improvement. The main intention of this document make documentation of Iroha project reasonable, suitable and code connected.

## documentation proposal for the project folders
Section describes where will be `README.md` files in the project and minimum what they should provide. `///` provides thoughts about the improvement of the current structure.

```
cmake
  └── README.md
        * description of dependencies (repository with upstream ref, license, use case in the project)

docker
  └── README.md
        * scripts description
        * reference to documentation for different use cases

docs
  └── README.md
        * description of documentation format
        * link to compiled online version

example
  └── README.md
        * how to run example
        /// maybe move example from root to docs

iroha-cli
  └── README.md
        * description
        * reference to documentation with usage

irohad
  └── README.md
      │  * common description
      │  * intercomponent references
      │  * reference to use case documentation and example of usage
      │  * link to contribution guide
      │  * link to architecture documentation
      └── ametsuchi
      │   └── README.md
      │
      └── consensus
      │    └── README.md
      │    │
      │    └── YAC
      │        └── README.md
      │
      └── main
      │   └── README.md
      │
      └── network
          └── README.md
      │
      └── ordering
      │   └── README.md
      │    /// move orderings to consensus maybe
      │
      └── simulator
      │   └── README.md
      │
      └── torii
      │   └── README.md
      │
      └── validation
          └── README.md

libs /// rename to util
  └── README.md
        * description of internal folders

schema
  └── README.md
        * description model objects
        * reference to shared_model
        * reference to bindings

shared_model
  └── README.md
        * general information
        * reference to schema
        * reference to bindings
      └── backend
      │   └── README.md
      │
      └── bindings
      │   └── README.md
      │
      └── builders
      │   └── README.md
      │
      └── converters
      │   └── README.md
      │
      └── cryptography
      │   └── README.md
      │
      └── interfaces
      │   └── README.md
      │
      └── utils
      │   └── README.md
      │
      └── validators
          └── README.md

test
  └── README.md
        * common folder schema
        * cmake test target
      │
      └── framework
          └── README.md
```
# documentation application
The section provides rule of thumb for pieces of documentation and what it should include.

- doxygen
  * class documentation (+ methods, fields)
  * dependencies of classes
  * header includes
  * namespaces
  
- readme.md
  * description of component
  * overview how it works
  * references to external documentation
  * advice to introduction to the component

- readthedocs
  * general ideas that don't cover by separated readme
  * tutorials
  * glossaries
  * presentations

# references
Reference for documentation in other projects.

* https://github.com/google/leveldb/tree/master/port
* https://github.com/ripple/rippled/tree/develop/src
* https://github.com/boostorg/algorithm/blob/develop/minmax/index.html
* https://github.com/google/protobuf/tree/master/php
* https://github.com/postgres/postgres/tree/master/src/backend/executor
* https://github.com/stellar/stellar-core/tree/master/src/ledger
* https://github.com/stellar/stellar-core/tree/master/docs

**Comment by grimadas** [comment]
What are the implications of moving ordering to consensus, it will be tightly connected to consensus ? The rest LGTM

**Comment by Alexey-N-Chernyshov** [comment]
Great idea. I think it will significantly improve the comprehensiveness of documentation.

**Comment by l4l** [comment]
## Project structure

* cmake/README.md

I think it's better to describe an overall picture here as long as we may frequently change dependencies and forgot to update readme file (at least for beginning)

* network
* ordering

That dirs (at least its components) often confuses me, looks like mixed files up here:
![screenshot_20180213_124042](https://user-images.githubusercontent.com/5658339/36143100-30103ce6-10bb-11e8-9b53-2aa902c29fde.png)


* irohad/consensus/YAC

Imo lowercase for `YAC` dir is more consistent

* shared_model/

I don't really like (or maybe understand) that name. What the meaning of `shared` here? Imo it's better name it just as `model` (, or also can be suitable: `objects`, `types`, `entities`)

* shared_model/
    * bindings
    * builders
    * converters
    * interfaces
    * utils
    * validators

These directory names are plurals, and it's quite inconsistent with the `irohad/*` directories. Quick search on the web shows plural (instead of singular) is more preferred by devs.

* test

Not really clear what should be written here. Imo that can be omitted

* scripts

Seems that it's missing here. Imo `README` should be here, based on docs files. Then it possible to move the rest of the files in docs to the `INSTALLING` file at the root

## Docs description

* readme
Would be nice to add *why* that component required, its purposes, etc
Not sure it's needed *how it works* section. Can be problems on updating
Advice to introduction to the component* - not clear for me, may you explain a bit?

* readthedocs

Should be self-sustained, thus include installation, launching, etc. End-users won't read the docs at the code base, it's only for devs/contributors
*presentations* - link to the additional materials maybe?


&nbsp;

The rest looks good

**Comment by muratovv** [comment]
@grimadas In fact, ordering is the part of a consensus algorithm and in this case, it will be more consistent with architecture what we have.

**Comment by muratovv** [comment]
@l4l 
>Imo lowercase for YAC dir is more consistent
Of course, it is a bug.

>Would be nice to add why that component required
Yes, good point.

>readthedocs
Well, the idea is the following we will handle documentation and code in the one repository. Also, we have readthedocs cite, where we deploy current state of the documentation.

>presentations - link to the additional materials maybe?
Some repositories have presentations and pdf inside the project. We may use links, but in this case, we will not guarantee the consistency of presentations/pdf/etc. 

>test 
>Not really clear what should be written here. Imo that can be omitted
Idea is to describe folder structure, playground zones and contribution guide.

>scripts
>Imo README should be here, based on docs files
It is possible to make cross-references for the purpose.

**Comment by l4l** [comment]
Besides would be nice to extract `client.{c,h}pp` somewhere as long as it can be useful for devs

**Comment by nickaleks** [comment]
It is also important to create auto-generated docs for proto files. There are tools like Doxygen, but for protobuf, and they will allow us to keep documentation up to date.

**Comment by neewy** [comment]
Please close this issue if it is resolved
